namespace IWebsocketClientLite.PCL
{
    public enum ConnectionStatus
    {
        Initialized,
        ConnectingToTcpSocket,
        TcpSocketConnected,
        ConnectingToSocketStream,
        SocketStreamConnected,
        SecureSocketStreamConnected,
        SendingHandshakeToWebsocketServer,
        HandshakeCompletedSuccessfully,
        WebsocketConnected,
        Disconnected,
        ForcefullyDisconnected,
        Close,
        DataframeReceived,
        Aborted,
        Text,
        Binary,
        SendComplete,
        SendError,
        DeliveryAcknowledged,
        SingleFrameSending,
        MultiFrameSendingContinue,
        MultiFrameSendingBegin,
        MultiFrameSendingFirst,
        Continuation,
        MultiFrameSendingLast,
        FrameDeliveryAcknowledged,
        ConnectionFailed,
        SendPing,
        PingReceived,
        SendPong,
        PongReceived
    }
}
