namespace IWebsocketClientLite.PCL
{
    public enum ConnectionStatus
    {
        Initialized,
        ConnectingToTcpSocket,
        TcpSocketConnected,
        SendingHandshakeToWebsocketServer,
        HandshakeCompletedSuccessfully,
        WebsocketConnected,
        Disconnected,
        ForcefullyDisconnected,
        Disconnecting,
        Aborted,
        Sending,
        SendComplete,
        SendError,
        DeliveryAcknowledged,
        MultiFrameSendingSingle,
        MultiFrameSendingBegin,
        MultiFrameSendingFirst,
        MultiFrameSendingContinue,
        MultiFrameSendingLast,
        FrameDeliveryAcknowledged,
        ConnectionFailed,
        ReceivedPing,
        SendPong,
    }
}
